# General Settings
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

# THE MASTER SWITCH
# Change this to 'prod' when you are ready to push to Hugging Face
spring.profiles.active=dev

# Email Configuration
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=8d7650aac5d01c
spring.mail.password=3ea154ec602885
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.jwt.secret=ThisIsAMuchLongerSecretKeyForSecurityPurposes2026!