# General Settings
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

# THE MASTER SWITCH
# Change this to 'prod' when you are ready to push to Hugging Face
spring.profiles.active=dev

# --- MAIL CONFIGURATION ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587

# Use variables so you don't leak your real email on GitHub
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

# Essential SMTP security settings
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Timeouts (prevents the app from hanging if Gmail is slow)
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

app.jwt.secret=ThisIsAMuchLongerSecretKeyForSecurityPurposes2026!