spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
# This creates a file named "bankdb.mv.db" in your project folder
spring.datasource.url=jdbc:h2:file:./data/bankdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# This ensures your tables are created automatically
spring.jpa.hibernate.ddl-auto=update
# Allow us to see the database in the browser
spring.h2.console.enabled=true
# Email Configuration (Example using Mailtrap.io)
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=8d7650aac5d01c
spring.mail.password=3ea154ec602885
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true